name: .Net core

on:
  push:
    branches:
      - main

jobs:
  provision:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AD_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
        
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      # - name: fmt terraform
      #   working-directory: ./terraform
      #   run: terraform fmt -check
  
      - name: terraform init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: terraform validate
        working-directory: ./terraform
        run: terraform validate -no-color

      - name: terraform plan
        working-directory: ./terraform
        continue-on-error: true
        run: |
          terraform plan -out "tf_plan" -input=false
          ls -l
          pwd
#         terraform show "tf_plan"

      - name: upload TF plan as artifact
        uses: actions/upload-artifact@v2
        with:
            name: tf_paln
            path: {{pwd}}/terrafrom
            if-no-files-found: error 
            retention-days: 7  

      - name: terraform apply
        working-directory: ./terraform
        run: terraform apply -input=false -auto-approve

  build-and-deploy:
    needs: provision
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
        node: [10.16.3,14,16,18]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}

      - name: Install dependencies in client app
        working-directory: Source\Tailwind.Traders.Web\ClientApp
        run: | 
          npm Install

      - name: build and publish with dotnet
        working-directory: Source\Tailwind.Traders.Web
        run: | 
          dotnet build --configuration Release
          dotnet publish -c Release -o publish

      - name: 'login via azure cli'
        uses: azure/login@v1
        with:
          creds: ${{secrets.azure_cred}}

      - name: Run Azure webapp deploy action
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-westus-test    
          
          package: TailwindTraders.Website/Source/Tailwind.Traders.Web/publish

      - name: Azure logout]
        run: | 
          az logout




